services:

  # https://hub.docker.com/_/drupal
  # admin // *V3FYY8fdK2rBYT
  drupal:
    image: drupal:10-php8.3-apache
    # image: drupal:10-php8-fpm
    container_name: drupal
    restart: always
    ports:
      - 8080:80
    environment:
      DB_NAME: "db01"
      DB_USER: "user01"
      DB_PASS: "passw0rd"
      DB_HOST: "mariadb"
      S3_BUCKET: ""
      S3_ROOT_FOLDER: "local"
      # S3FS_ACCESS_KEY: ""
      # S3FS_SECRET_KEY: ""
      SITE_NAME: "Drupal Core - LOCAL"
      # API_KEY: ""
    volumes:
      - drupal:/var/www/html
    depends_on:
      - mariadb
      - redis
    networks:
      - app-network
      - data-network

networks:
  app-network:
    driver: bridge
  data-network:
    driver: bridge

volumes:
  drupal:
  # db:
