up:
	docker compose up -d

down:
	docker compose down

logs:
	docker compose logs -f

restart:
	docker compose restart

clean:
	docker compose down -v

logs-drupal:
	docker compose logs -f drupal

logs-mariadb:
	docker compose logs -f mariadb

logs-redis:
	docker compose logs -f redis

shell:
	docker compose exec drupal bash

drush:
	docker compose exec drupal drush
