

build:
	docker build . -t postgresql -f bitnami-vector.dockerfile

tag:
	docker tag postgresql ghcr.io/scriptonbasestar/bitnami-pg-vector:16.4.0-debian-12-r2

push:
	docker push ghcr.io/scriptonbasestar/bitnami-pg-vector:16.4.0-debian-12-r2
