services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./app:/var/www
      - ./nginx/php-web.conf:/etc/nginx/conf.d/default.conf
      - ./.nginx.conf:/etc/nginx/conf.d/.nginx.conf
    ports:
    - 8080:80
    networks:
      - code-network
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: flarum-fpm.dockerfile
    image: flarum-fpm:1
    container_name: flarum
    volumes:
      - ./app:/var/www
    networks:
      - code-network
      - db-network
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.4
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=db01
      - MYSQL_USER=user01
      - MYSQL_PASSWORD=passw0rd
    volumes:
      - db:/var/lib/mysql
    networks:
      - db-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mariadb
    links:
      - mariadb:db
    ports:
      - 8081:80
    environment:
      PMA_USER: root
      PMA_PASSWORD: dockerPWDroot

  mailhog:
    image: mailhog/mailhog:latest
    ports:
#        - "1025:1025"
      - "8025:8025"
    expose:
      - 1025

networks:
  code-network:
      driver: bridge
  db-network:
    driver: bridge

volumes:
  db:
