version: '3.7'

services:
  consul-leader:
    image: consul
    command: agent -server -client=0.0.0.0 -bootstrap -ui
    volumes:
      - consul-data-leader:/consul/data
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'
    networks:
      - default
      - traefik-public
    deploy:
      labels:
        - traefik.frontend.rule=Host:consul.${DOMAIN}
        - traefik.enable=true
        - traefik.port=8500
        - traefik.tags=${TRAEFIK_PUBLIC_TAG:-traefik-public}
        - traefik.docker.network=traefik-public
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
        - traefik.frontend.auth.basic.users=${USERNAME}:${HASHED_PASSWORD}
      placement:
        constraints:
          - node.hostname == polypia-sheepdog1
  consul-replica:
    image: consul
    command: agent -server -client=0.0.0.0 -retry-join="consul-leader"
    volumes:
      - consul-data-replica:/consul/data
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'
    networks:
      - default
      - traefik-public
    deploy:
      replicas: ${CONSUL_REPLICAS:-3}
      placement:
        preferences:
          - spread: node.id
  traefik:
    image: traefik:v1.7
    ports:
      - 80:80
      - 443:443
    deploy:
      replicas: ${TRAEFIK_REPLICAS:-3}
      placement:
        constraints:
          - node.role == manager
          - node.hostname == polypia-sheepdog1
        preferences:
          - spread: node.id
      labels:
        - traefik.frontend.rule=Host:traefik.${DOMAIN}
        - traefik.enable=true
        - traefik.port=8080
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
        - traefik.frontend.auth.basic.users=${USERNAME}:${HASHED_PASSWORD}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      --docker
      --docker.swarmmode
      --docker.watch
      --docker.exposedbydefault=false
      --constraints=tag==traefik-public
      --entrypoints='Name:http Address::80'
      --entrypoints='Name:https Address::443 TLS'
      --consul
      --consul.endpoint="consul-leader:8500"
      --acme
      --acme.email=${EMAIL}
      --acme.storage="traefik/acme/account"
      --acme.entryPoint=https
      --acme.httpChallenge.entryPoint=http
      --acme.onhostrule=true
      --acme.acmelogging=true
      --logLevel=INFO
      --accessLog
      --api
    networks:
      - default
      - traefik-public
    depends_on:
      - consul-leader
  # nexus3:
  #   image: sonatype/nexus3:latest
  #   container_name: nexus3
  #   deploy:
  #     replicas: 1
  #     labels:
  #       - traefik.frontend.rule=Host:nexus.${DOMAIN}
  #       - traefik.enable=true
  #       - traefik.port=8081
  #       - traefik.tags=${TRAEFIK_PUBLIC_TAG:-traefik-public}
  #       - traefik.docker.network=traefik-public
  #       # Traefik service that listens to HTTP
  #       - traefik.redirectorservice.frontend.entryPoints=http
  #       - traefik.redirectorservice.frontend.redirect.entryPoint=https
  #       # Traefik service that listens to HTTPS
  #       - traefik.webservice.frontend.entryPoints=https
  #       # - traefik.frontend.auth.basic.users=${USERNAME}:${HASHED_PASSWORD}
  #     placement:
  #       constraints:
  #         - node.hostname == polypia-sheepdog1
  #   networks:
  #     - traefik-public
 
volumes:
  consul-data-leader:
  consul-data-replica:

networks:
  traefik-public:
    external: true


  # #xwiki
  # xw-work:
  #   image: xwiki:lts-mysql-tomcat
  #   environment:
  #     - VIRTUAL_HOST=tutorial2.polypia.net
  #     - LETSENCRYPT_HOST=tutorial2.polypia.net,cheatsheet.polypia.net
  #     - LETSENCRYPT_EMAIL=contact@scriptonbasestar.com
  #     - DB_USER=web_user
  #     - DB_PASSWORD=a+cdefE2^jkEmARp
  #     - DB_DATABASE=web_tutorial2
  #     - DB_HOST=data-mysql
  #     # 8080
  #   networks:
  #     - polypia-backend
  #     - polypia-frontend
  #   # links:
  #   external_links:
  #     - data-mysql:polypia-backend
  #     - nginx-proxy:polypia-frontend
  #   # depends_on:
  #   #   - data-mysql
  #   #   - nginx-proxy
  #   volumes:
  #     - /work/web/xw-tutorial:/usr/local/xwiki