version: v0.13.0

dsn: memory

serve:
  public:
    base_url: https://auth.gorisa.kr/
    cors:
      enabled: true
  admin:
    base_url: https://admin.gorisa.kr/

selfservice:
  default_browser_return_url: https://gorisa.kr/welcome
  allowed_return_urls:
    - http://127.0.0.1:4455
    - http://localhost:19006/Callback
    - exp://localhost:8081/--/Callback

  methods:
    # https://www.ory.sh/docs/concepts/password-policy
    password:
      enabled: true
      config:
        min_password_length: 8
        identifier_similarity_check_enabled: true
        haveibeenpwned_enabled: true
    totp:
      config:
        issuer: Kratos
      enabled: true
    lookup_secret:
      enabled: true
    link:
      enabled: true
    code:
      enabled: true
    oidc:
      config:
        # google?
        # naver, kakao
        # 국내 위주 역사 서비스니까... 외국인은 안정화 후에 나중에 받는다.
        # 개인인증 기능을 추가할 수 있ㅇ나?
        providers:
          - id: gorisa-discourse-client
            provider: generic
            client_id: gorisa-discourse-client
            # generate by openssl rand -base64 32
            client_secret: +OttJb/SkA1It29PMo8aJCE2pSoDJxTvwOlPd1HukiY=
            issuer_url: https://accounts.google.com # Replace this with the providers issuer URL
            mapper_url: "base64://{YOUR_BASE64_ENCODED_JSONNET_HERE}"
            # Alternatively, use an URL:
            # mapper_url: https://storage.googleapis.com/abc-cde-prd/9cac9717f007808bf17
            grant_types:
              - authorization_code
              - refresh_token
            scope:
              - openid
              - profile
              - email
            # supported scopes can be found in your providers dev docs
      enabled: true

  flows:
    error:
      ui_url: https://auth.gorisa.kr/error

    settings:
      ui_url: https://auth.gorisa.kr/settings
      privileged_session_max_age: 15m
      required_aal: highest_available

    recovery:
      enabled: true
      ui_url: https://auth.gorisa.kr/recovery
      use: code

    verification:
      enabled: true
      ui_url: https://auth.gorisa.kr/verification
      use: code
      after:
        default_browser_return_url: https://auth.gorisa.kr/welcome

    logout:
      after:
        default_browser_return_url: https://auth.gorisa.kr/login

    login:
      ui_url: https://auth.gorisa.kr/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: https://auth.gorisa.kr/registration
      after:
        password:
          hooks:
            - hook: session
            - hook: show_verification_ui

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true

feature_flags:
  use_continue_with_transitions: true
