services:
  redis:
    image: bitnami/redis:7.4
    container_name: redis_dev
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-passw0rd}
    ports:
      - "6379:6379"
    # volumes:
    #   - redis:/data
    networks:
      - data-network

networks:
  app-network:
    driver: bridge
  intra-network:
    driver: bridge
  data-network:
    driver: bridge

# volumes:
#   redis:
