
init:
	@echo "clone or reset containers"
	git clone https://github.com/go-kratos/kratos.git
	git clone https://github.com/ScriptonBasestar-containers/ory-kratos-selfservice-ui-node.git
	git clone https://github.com/ScriptonBasestar-containers/ory-kratos-selfservice-ui-react-nextjs.git
	git clone https://github.com/go-kratos/examples.git

build:

deploy:
