
init:
	@echo "clone or reset containers"
	git clone https://github.com/seatonjiang/kratos.git
	git clone https://github.com/ScriptonBasestar-containers/kratos-selfservice-ui-node.git
	git clone https://github.com/ScriptonBasestar-containers/ory-kratos-selfservice-ui-react-nextjs.git


build:


deploy:
