services:
  # https://hub.docker.com/r/gollumwiki/gollum
  gollum:
    build:
      context: .
      dockerfile: Dockerfile
    # image: gollumwiki/gollum
    restart: always
    ports:
      - 4567:4567
    volumes:
      # - ./wiki:/wiki
      - ./docker-entrypoint.sh:/docker-entrypoint.sh
      - gollum:/wiki
    entrypoint: ["/docker-entrypoint.sh"]
    command: ["gollum", "/wiki"]
    # command: ["gollum", "/home/www-data"]


volumes:
  gollum:
