services:
  # https://hub.docker.com/r/gollumwiki/gollum
  gollum:
    image: gollumwiki/gollum
    restart: always
    ports:
      - 4567:4567
    volumes:
      - ./wiki:/wiki
      # - gollum:/wiki
    command: ["gollum", "/wiki"]

# volumes:
  # gollum:
