services:

  wordpress:
    # image: wordpress:php8.3-apache
    image: wordpress:6-php8.3-apache
    # image: wordpress:6-php8-fpm
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: user01
      WORDPRESS_DB_PASSWORD: passw0rd
      WORDPRESS_DB_NAME: db01
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
      - redis
      - wp-cli
    networks:
      - code-network
      - db-network

  wp-install:
    image: wordpress:cli
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: user01
      WORDPRESS_DB_PASSWORD: passw0rd
      WORDPRESS_DB_NAME: db01
    # command: ["core", "install", "--url=http://localhost:8080", "--title=My WordPress Site", "--admin_user=admin", "--admin_password=password", "--]
    command: ["/run-wp-cli.sh"]
    volumes:
      # - entrypoint.sh:/entrypoint.sh
      - run-wp-cli.sh:/run-wp-cli.sh
      - wordpress:/var/www/html
    depends_on:
      - mariadb
      - redis
    networks:
      - code-network
      - db-network

  mariadb:
    image: mariadb:10.4
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=db01
      - MYSQL_USER=user01
      - MYSQL_PASSWORD=passw0rd
    volumes:
      - db:/var/lib/mysql
    networks:
      - db-network
  
  redis:
    image: bitnami/redis
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=password
    networks:
      - db-network

networks:
  code-network:
      driver: bridge
  db-network:
    driver: bridge

volumes:
  wordpress:
  db:
