version: '3.7'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html

  mariadb:
    image: mariadb:10.4
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=db01
      - MYSQL_USER=user01
      - MYSQL_PASSWORD=passw0rd
    volumes:
      - db:/var/lib/mysql
    networks:
      - db-network
  
  redis:
    image: bitnami/redis:5.0
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=password

volumes:
  wordpress: