services:
  jenkins: 
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    environment:
      - TZ=Asia/Seoul
    user: root
    privileged: true
    ports:
      - 8080:8080
      - 50000:50000
    # volumes:
    #   - ./jenkins/config:/var/jenkins_home
    #   - /var/run/docker.sock:/var/run/docker.sock

    