services:
  postgres:
    image: postgres:15
    container_name: postgres_dev
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=${POSTGRES_DB:-db01}
      - POSTGRES_USER=${POSTGRES_USER:-user01}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-passw0rd}
      - ENABLE_IPV6=true
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - data-network

networks:
  app-network:
    driver: bridge
  intra-network:
    driver: bridge
  data-network:
    driver: bridge

volumes:
  postgres:
