services:
  redis:
    image: redis:8.2-alpine
    container_name: redis_dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD:-passw0rd}
    volumes:
      - redis:/data
    networks:
      - data-network
    # Health check
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

networks:
  app-network:
    driver: bridge
  intra-network:
    driver: bridge
  data-network:
    driver: bridge

volumes:
  redis:
