services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_dev
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      # Official PostgreSQL uses /docker-entrypoint-initdb.d/
      - ${PROJECT_HOME}/devbox/config/postgres/init-user.sql:/docker-entrypoint-initdb.d/00-user.sql
      # Data volume (official PostgreSQL path)
      - postgres:/var/lib/postgresql/data
    environment:
      # Official PostgreSQL environment variables
      - POSTGRES_PASSWORD=passw0rd
      # - POSTGRES_USER=postgres  # default user
      # - POSTGRES_DB=postgres    # default database
    networks:
      - data-network
    # Health check
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge
  intra-network:
    driver: bridge
  data-network:
    driver: bridge

volumes:
  postgres:

# pg_hba.conf
# host     all             all             0.0.0.0/0               md5
# host     all             all             ::/0                    md5
# local    all             all                                     md5
# host     all             all        127.0.0.1/32                 md5
# host     all             all        ::1/128                      md5
