services:
  postgres:
    image: bitnami/postgresql:15
    container_name: postgres_dev
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
    # docker-entrypoint-initdb.d/
    # docker-entrypoint-preinitdb.d/
      - ${PROJECT_HOME}/devbox/config/postgres/init-user.sql:/docker-entrypoint-initdb.d/00-user.sql
#      - ${PROJECT_HOME}/devbox/config/postgres/init-user-bitnami.sh:/docker-entrypoint-initdb.d/00-init-user.sh
      # /opt/bitnami/postgresql/conf
      # - postgres:/bitnami/postgresql
    environment:
      - debug=true
#      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=passw0rd
#      - POSTGRESQL_DATABASE=discourse_db
      - POSTGRESQL_POSTGRES_PASSWORD=passw0rd
    networks:
      - data-network

networks:
  app-network:
    driver: bridge
  intra-network:
    driver: bridge
  data-network:
    driver: bridge

volumes:
  postgres:

# pg_hba.conf
# host     all             all             0.0.0.0/0               md5
# host     all             all             ::/0                    md5
# local    all             all                                     md5
# host     all             all        127.0.0.1/32                 md5
# host     all             all        ::1/128                      md5
