services:
  kratos-migrate:
    image: oryd/kratos:v1.2
    container_name: kratos-migrate
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - kratos-config:/etc/config/kratos
#      - type: bind
#        source: ./config/kratos
#        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - intra-network
  kratos-selfservice-ui-node:
#    image: oryd/kratos-selfservice-ui-node:v1.2.0
    image: archmagece/ory-kratos-selfservice-ui-node
    container_name: kratos-ui
    environment:
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_BROWSER_URL=http://127.0.0.1:4433/
      - COOKIE_SECRET=changeme
      - CSRF_COOKIE_NAME=ory_csrf_ui
      - CSRF_COOKIE_SECRET=changeme
    networks:
      - intra-network
    restart: on-failure
  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v1.2
    container_name: kratos_dev
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos.dev.yml --dev --watch-courier
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - kratos-config:/etc/config/kratos
#      - type: bind
#        source: ./config/kratos
#        target: /etc/config/kratos
    networks:
      - intra-network
  mailslurper:
#    image: oryd/mailslurper:latest-smtps
#    image: tsle/mail-mailslurper-arm64:latest
    image: bluesinc/mailslurper
    container_name: mailslurper
    ports:
      - '4436:4436'
      - '4437:4437'
    networks:
      - intra-network

networks:
  intra-network:
    driver: bridge

volumes:
  kratos-sqlite:
  kratos-config:
    name: kratos-config
  ##    external: true
  mediawiki-config:
    name: mediawiki-config
