services:
  mariadb:
    image: mariadb:11.8
    container_name: mariadb_dev
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpass}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-db01}
      - MYSQL_USER=${MYSQL_USER:-user01}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-passw0rd}
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - data-network

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin:latest
  #   depends_on:
  #     - mariadb
  #   links:
  #     - mariadb:db
  #   ports:
  #     - 8081:80
  #   environment:
  #     PMA_USER: root
  #     PMA_PASSWORD: dockerPWDroot
  #   networks:
  #     - data-network

networks:
  app-network:
    driver: bridge
  intra-network:
    driver: bridge
  data-network:
    driver: bridge

volumes:
  mariadb:
