version: '3.8'

services:
  devpi:
    build:
      context: .
      args:
        - INSTALL_WEB=${INSTALL_WEB:-true}
        - INSTALL_CONSTRAINED=${INSTALL_CONSTRAINED:-false}
        - INSTALL_FINDLINKS=${INSTALL_FINDLINKS:-false}
        - INSTALL_JENKINS=${INSTALL_JENKINS:-false}
        - INSTALL_LOCKDOWN=${INSTALL_LOCKDOWN:-false}
    image: devpi/server:latest
    container_name: devpi-server
    ports:
      - "3141:3141"
    volumes:
      - ./devpi_data:/app/data
      - ./logs:/app/logs
    environment:
      - DEVPI_HOST=0.0.0.0
      - DEVPI_PORT=3141
      - DEVPI_WEB_THEME=semantic-ui
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3141/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - devpi-network

networks:
  devpi-network:
    driver: bridge 