services:
  # Nextcloud - Self-hosted productivity platform
  # https://hub.docker.com/_/nextcloud
  nextcloud:
    image: nextcloud:29
    container_name: ${NEXTCLOUD_CONTAINER_NAME:-nextcloud}
    restart: unless-stopped
    ports:
      - "${WEB_PORT:-8210}:80"
    environment:
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: passw0rd

      REDIS_HOST: redis
      REDIS_HOST_PORT: 6379

      MYSQL_HOST: mariadb
      MYSQL_DATABASE: db01
      MYSQL_USER: user01
      MYSQL_PASSWORD: passw0rd

      # Optional settings:
      # NEXTCLOUD_TRUSTED_DOMAINS: example.com
      # NEXTCLOUD_UPLOAD_MAX_FILESIZE: 4G
      # NEXTCLOUD_MAX_FILE_UPLOADS: 20
    volumes:
      - nxc_root:/var/www/html
      - nxc_apps:/var/www/html/custom_apps
      - nxc_data:/var/www/html/data
      - nxc_themes:/var/www/html/themes
      # Hook directories (optional):
      # - ./app-hooks/pre-installation:/docker-entrypoint-hooks.d/pre-installation
      # - ./app-hooks/post-installation:/docker-entrypoint-hooks.d/post-installation
      # - ./app-hooks/pre-upgrade:/docker-entrypoint-hooks.d/pre-upgrade
      # - ./app-hooks/post-upgrade:/docker-entrypoint-hooks.d/post-upgrade
      # - ./app-hooks/before-starting:/docker-entrypoint-hooks.d/before-starting
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - app-network
      - data-network

  mariadb:
    image: mariadb:11.8
    container_name: nextcloud-mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: db01
      MYSQL_USER: user01
      MYSQL_PASSWORD: passw0rd
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - data-network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: nextcloud-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - data-network

networks:
  app-network:
    driver: bridge
  data-network:
    driver: bridge

volumes:
  nxc_root:
  nxc_apps:
  nxc_data:
  nxc_themes:
  mariadb-data:
  redis-data:
