---
###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

# List of users
users:
  a01:
    disabled: false
    displayname: "a01"
    password: "$argon2id$v=19$m=65536,t=3,p=4$xhTflorwjFFFlqvlt2SK5Q$BzAObdCjRkJewC/mwn1TuyExSkmoks2qo18BwQInncU"
    email: a01@a.com
    groups:
      - admins
      - dev
...
