name: Build and Push Services

# on:
#   push:
#     paths:
#       - 'service1/**'
#       - 'service2/**'
#   pull_request:
#     paths:
#       - 'service1/**'
#       - 'service2/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: service1
            path: service1
          - name: service2
            path: service2

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ./${{ matrix.service.path }}
        file: ./${{ matrix.service.path }}/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service.name }}:latest
      if: ${{ github.event.head_commit.message == '' || contains(github.event.head_commit.message, matrix.service.path) }}
