up:
	docker compose up -d

down:
	docker compose down

logs:
	docker compose logs -f

restart:
	docker compose restart

clean:
	docker compose down -v

logs-joomla:
	docker compose logs -f joomla

logs-mariadb:
	docker compose logs -f mariadb

logs-redis:
	docker compose logs -f redis

shell:
	docker compose exec joomla bash
